### ISSUE TITLE
Minor docstring clarification

### ISSUE THREAD

**Issue by bdarcus** [mclear-tools/citar-capf#1]
https://github.com/mclear-tools/citar-capf/blob/3f7b96d9b05ef17801918c1c86bd12e29553db2c/citar-capf.el#L42

I'm not sure how you want to clarify this, or I would submit a tiny PR, but note:

1. As I use it in citar, parsebib parses bibtex, biblatex and csl json files.
2. It can be multiple files.

**Comment by mclearc** [comment]
I think 0026bd5ae7d5cc1a3d3e140d34039aaec0d92043 fixes this but let me know if not.
