### ISSUE TITLE
config example not setting capf correctly

### ISSUE THREAD

**Issue by bdarcus** [mclear-tools/citar-capf#2]
Picking up where we earlier left off, in the hopes I can get this working, or it might help with the README instructions.

I do plan to test it with emacs -Q; I just need more time (maybe tomorrow).

If I add your `use-package` example, suitably modified for doom ...

### Org

Value of `completion-at-point-functions`:

```elisp
Its value is (pcomplete-completions-at-point t)
Local in buffer test.org; global value is 
(tags-completion-at-point-function citar-capf)
```

I do get corfu to activate with the citar completion. But if I hit `RET` on a candidate, it does not insert the key, but instead adds a newline to the buffer.

Aside: with the private doom corfu module I'm using, for other capfs (for example, in lisp buffers), when I highlight a candidate, it presents a preview, and when I hit `RET` it behaves as expected (inserts the candidate).

### LaTeX

```elisp
Its value is (TeX--completion-at-point t)
Local in buffer test.tex; global value is 
(tags-completion-at-point-function citar-capf)
```

Here I get no matches.

### Markdown

No matches.

```elisp
Its value is (citar-capf t)
Local in buffer test.md; global value is 
(tags-completion-at-point-function citar-capf)
```

Any suggestions? Is that setup as you expect with the variable?

**Comment by mclearc** [comment]
I really have no idea why you're having the keybinding issue. I don't see why/how citar-capf would alter your keybinds for completion. 

I was thinking though of making citar-capf a minor mode to make it easier to load in deferred loading scenarios. I could try setting a keymap and see if that helps. 

Ideally `citar-capf` goes before the other completion frameworks. This isn't going to be consistent if you have it loading after those modes i've noticed. So one thing to check is whether you can add a hook to loading markdown and tex that runs when those modes are first loaded:

```emacs-lisp
(defun citar-capf-hook () (add-hook 'completion-at-point-functions #'citar-capf -100 t))
  :config
  ;; Add hooks
(with-eval-after-load 'latex-mode
  (add-hook 'tex-mode-hook #'citar-capf-hook)
  (add-hook 'latex-mode-hook #'citar-capf-hook)
  (add-hook 'reftex-mode-hook #'citar-capf-hook))

(with-eval-after-load 'markdown-mode
  (add-hook 'markdown-mode-hook #'citar-capf-hook))

 (with-eval-after-load 'org-mode
(add-hook 'org-mode-hook #'citar-capf-hook))
```

EDIT: the reason you're getting no matches in latex and markdown modes is that the other completion table is clobbering citar-capf. This is why it is important that it get added first in the list (hence the `-100` depth value).

**Comment by mclearc** [comment]
FYI: I added a minor mode with new setup instructions that seem more reliable. See 16b5bad3cf6074f554d89ea7a05edcea7d939839 for details.

**Comment by bdarcus** [comment]
If I set the minor mode with a buffer open, it seems to set the capf correctly.

If I switch to another buffer, say in another major-mode, it doesn't. I have to deactivate and reactivate.

Do you see that?

**Comment by mclearc** [comment]
I'm not seeing that. I can ping pong between an elisp, fundamental, org, and markdown buffer and the org and markdown completion works as expected.

**Comment by bdarcus** [comment]
OK; well that's good. Must be something with my system.

I'll take a closer look later, probably tomorrow.

EDIT: in the meantime, I've [reported](https://discourse.doomemacs.org/t/new-completion-corfu-module/2685/3) the bug on the doom discourse, assuming it's specific to doom, and have tried to setup lambda-emacs instead, though [got stuck](https://github.com/Lambda-Emacs/lambda-emacs/issues/2).

**Comment by mclearc** [comment]
FYI -- this seems to work from me with a minimal (basically emacs -Q with config necessary to load markdown, org, citar, corfu) setup. I noticed no issues with keybindings. Both return and tab complete and insert the candidate as expected. 

<img width="626" alt="Screen Shot 2022-05-17 at 11 40 00" src="https://user-images.githubusercontent.com/1502422/168852427-e93efbdd-1215-4e4e-bc44-abff00283af2.png">

**Comment by bdarcus** [comment]
May as well close this, and assume some weird doom conflict.

**Comment by bdarcus** [comment]
Can you post the config file on a gist, or embedded here?

**Comment by mclearc** [comment]
Try this (note you'll have to set the variables)

```emacs-lisp
;;; CAPF Test
;;;; Set vars
(setq lem-bibliography (concat (getenv "HOME") "/Dropbox/Work/bibfile.bib"))
(setq lem-bib-notes (concat (getenv "HOME") "/Dropbox/Work/projects/notebook/content-org/ref-notes"))
;; Set citar library path
(with-eval-after-load 'citar
  (setq citar-library-paths '("/Users/roambot/Library/Mobile Documents/iCloud~com~sonnysoftware~bot/Documents/be-library")))

;;;; Citar
(use-package citar
  :straight (:host github :repo "bdarcus/citar")
  :custom
  (citar-bibliography `(,lem-bibliography))
  (org-cite-global-bibliography `(,lem-bibliography))
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  :config
  ;; edit notes
  (setq citar-notes-paths `(,lem-bib-notes)))

;;;; Markdown
(use-package markdown-mode)

;;;; Org-Cite
;; Eventually this should be a full replacement for org-ref
(use-package oc
  :straight nil
  :after org
  :config
  (setq org-cite-global-bibliography `(,lem-bibliography))
  (setq org-cite-export-processors
        '((beamer csl)
          (latex csl)
          (t csl))))

;; Currently only using csl
(use-package oc-csl
  :straight nil
  :after oc
  :init
  ;; make sure to download csl
  ;; https://citationstyles.org
  ;; https://github.com/citation-style-language
  ;; repos for styles & locales
  (setq org-cite-csl-styles-dir "~/.local/share/csl/styles")
  (setq org-cite-csl-locales-dir "~/.local/share/csl/locales"))

;;;; Citeproc
(use-package citeproc
  :straight (:host github :repo "andras-simonyi/citeproc-el")
  :after (oc oc-csl))

;;;; Corfu
(use-package corfu
  :straight (:type git :host github :repo "minad/corfu")
  :hook
  (after-init . global-corfu-mode)
  :custom
  ;; auto-complete
  (corfu-auto t))

;;;; Citar-Capf
(use-package citar-capf
  :straight (:local-repo "/Users/roambot/bin/lisp-projects/citar-capf")
  :hook ((org-mode markdown-mode tex-mode latex-mode reftex-mode) . citar-capf-mode))

(defun capf-citar-test ()
  (interactive)
  (progn
    (require 'citar-capf)
    (markdown-mode)
    (switch-to-buffer "*scratch*")))
```

you can probably skip the org-cite stuff if you just want to check that it works via markdown.

**Comment by bdarcus** [comment]
Alas, that's incomplete, as it doesn't include the straight setup and such.

I really wish emacs made this part easier.

**Comment by mclearc** [comment]
if you ever get lambda-emacs up and running 🤣 it has a command line switch `-test` that you can run that loads just the packages in lem-setup-test.el and the straight setup in init.el. Useful for testing without having to download all new packages etc.

**Comment by bdarcus** [comment]
You planning to add to MELPA, post an announcement on REDDIT?

**Comment by mclearc** [comment]
> You planning to add to MELPA, post an announcement on REDDIT?

Yes -- just need to find time. Hopefully in the next week or two. I've been working on https://github.com/mclear-tools/consult-notes a bit. If you have any interest in that package I appreciate any feedback.

**Comment by bdarcus** [comment]
Two related things on notes:

1. I started [this tiny project,](https://github.com/emacs-citar/citar-org-roam/tree/initial-commit), which led to ...
2. this issue at org-roam: https://github.com/org-roam/org-roam/issues/2207

2 is actually somewhat tricky conceptually and practically; please weigh in there if you have thoughts.

**Comment by bdarcus** [comment]
BTW, I'm not committed to finishing and releasing 1.

I am working on it mostly to ensure the notes API in citar is correct.

But it might be they're complementary. I agree using consult, with its support for narrowing and such, makes sense. I wasn't planning to add that to my package.

**Comment by bdarcus** [comment]
FYI, someone else confirmed a bug in doom that was causing the problem I was seeing with the capf (but later confirmed with others capfs).

https://discourse.doomemacs.org/t/new-completion-corfu-module/2685/15

**Comment by mclearc** [comment]
> You planning to add to MELPA, post an announcement on REDDIT?

FYI @bdarcus I've put an [announcement on reddit](https://www.reddit.com/r/emacs/comments/v7h5gq/new_package_citarcapf/). Hopefully I'll have time this weekend to submit it on melpa.

**Comment by bdarcus** [comment]
BTW, this major change will impact this code:

https://github.com/emacs-citar/citar/pull/628

But should be easy to adapt.
